logging:
  level: INFO
  loggers:
    com.pago.core: DEBUG

database:
  #properties:
  # hibernate.hbm2ddl.auto: create
  driverClass: org.postgresql.Driver
  user: postgres
  password: mysecretpassword
  url: jdbc:postgresql://localhost:5432/

transactiongateway:
  protocol: https://
  url: transactiongateway.dev.pagoservices.com
  port: 443
  token: "test"
