logging:
  level: INFO
  loggers:
    com.pago.core: DEBUG

database:
  #properties:
  # hibernate.hbm2ddl.auto: create
  driverClass: org.postgresql.Driver
  user: postgres
  password: mysecretpassword
  url: jdbc:postgresql://localhost:5432/

transactiongateway:
  url:
    localhost
  port:
    9050
  token:
    "test"