version: "3"
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
  quotes:
    image: openjdk:11
    depends_on:
      - postgres
      - bootstrap
    environment:
      LIFECYCLE: compose
    ports:
      - '8080'
      - 5005:5005
    volumes:
      - ./quotes-service/configs:/project/configs
      - ./quotes-service/target:/project/target
    command: java -jar /project/target/quotes-service.jar server /project/configs/compose.yml
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8082:8080
    depends_on:
      - 'quotes'
    environment:
      URL: http://localhost:8080/openapi.json
  easy-cors:
    image: pagoservices/easy-cors:latest
    depends_on:
      - 'quotes'
    environment:
      SERVICE_NAME: quotes
      SERVICE_PORT: '8080'
    ports:
      - 8080:80
  bootstrap:
    image: openjdk:11
    depends_on:
      - postgres
    environment:
      LIFECYCLE: compose
    volumes:
      - ./quotes-service/configs:/project/configs
      - ./quotes-service/target:/project/target
    command: java -jar /project/target/quotes-service.jar db migrate /project/configs/compose.yml
