package com.pago.core.quotes.dao.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.pago.core.quotes.dao.util.DynamoDBLocalDateTimeGenerator;
import lombok.Data;

import javax.validation.constraints.NotNull;
import java.time.Instant;
import java.time.LocalDateTime;

@Data
@DynamoDBTable(tableName="Name")
public class QuoteItem {

    public QuoteItem() {}

    @DynamoDBHashKey
    @DynamoDBGeneratedUuid(DynamoDBAutoGenerateStrategy.CREATE)
    @NotNull
    private String id;
    @DynamoDBAttribute
    @NotNull
    private String quote;
    @DynamoDBAttribute
    @NotNull
    @DynamoDBAutoGenerated(generator = DynamoDBLocalDateTimeGenerator.class)
    private String createDate;
}
